name: cardio_care
description: A heart health monitoring app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  cloud_firestore: ^5.6.8
  flutter_bluetooth_serial: ^0.4.0
  tflite_flutter: ^0.11.0
  url_launcher: ^6.2.4
  geolocator: ^14.0.1
  http: ^1.1.2
  google_maps_flutter: ^2.5.3
  uuid: ^4.3.3
  permission_handler: ^12.0.0+1
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/heart_risk_model.tflite