<<<<<<< HEAD
name: heart_health
description: Heart Health Monitoring App using Flutter & Firebase

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  tflite_flutter: ^0.11.0
  provider: ^6.1.2
  uuid: ^4.3.3
  animated_background: ^2.0.0
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^12.0.0+1
  cloud_firestore: ^5.6.8
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
=======
name: cardio_care
description: A heart health monitoring app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  cloud_firestore: ^5.6.8
  flutter_bluetooth_serial: ^0.4.0
  tflite_flutter: ^0.11.0
  url_launcher: ^6.2.4
  geolocator: ^14.0.1
  http: ^1.1.2
  google_maps_flutter: ^2.5.3
  uuid: ^4.3.3
  permission_handler: ^12.0.0+1
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
>>>>>>> 1af2eb8667a4b1c17d7920c43c21974f62325751
    - assets/heart_risk_model.tflite